#!/usr/bin/env perl

use strict;
use warnings;

use DBIx::Class::Schema::Loader qw/make_schema_at/;

make_schema_at(
    "EmberMojo::Schema",
    {
        debug => 1,
        dump_directory => 'lib',
    },
    [ 'dbi:mysql:database=embermojo', 'root' ],
);

